---
title: "SCC and policy choice under uncertainty"
author: "Bri Baker, Mikel Irigoyen"
date: "5/17/2021"
output: html_document
---

#### ANNA DO NOT READ THIS DOCUMENT IT IS NOT FOR U


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(decisionSupport)

```

## Data Setup

```{r data}

war <- read_csv(here("warming.csv")) %>%  # add warming data
  rename("id" = "X1")

dam <- read_csv(here("damages.csv")) # add damages data

pulse <- 35000000000 # tons of carbon

```

## Question 1

```{r damage function}
dam <- dam %>% 
  mutate(warm2 = warming^2) # make quadratic term

dam_deg <- lm(damages ~ 0 + warming + warm2, data = dam) # fit quadratic

dam_deg_a <- dam_deg$coefficients[[2]] # squared term
dam_deg_b <- dam_deg$coefficients[[1]] # second term
  
ggplot(dam, aes(x = warming, y = damages)) + # plot
  geom_point() + # scatter
  geom_smooth()+
  labs(title="Damage Function",
        x ="Change in Global mean Temp", y = "Damages ($)")+
  theme_minimal()
# plot line

## how to inline reference the square term???

```

damage = `r dam_deg_a`warming^2^ + `r dam_deg_b`warming


## Question 2

```{r graphs}

war <- war %>% 
  mutate(damages_baseline = dam_deg_a*warming_baseline^2 + dam_deg_b*warming_baseline,
         damages_pulse = dam_deg_a*warming_pulse^2 + dam_deg_b*warming_pulse,
         diff_damages = damages_pulse-damages_baseline,
         diff_ton = diff_damages/pulse
         ) # calc damages

ggplot(war, aes(x = year, y = damages_baseline))+
  geom_point() +
  labs(title="Damages Without the Pulse",
        x ="Year", y = "Damages ($)")+
  theme_minimal() 

ggplot(war, aes(x = year, y = damages_pulse))+
  geom_point() +
  labs(title="Damages With the Pulse",
        x ="Year", y = "Damages ($)")+
  theme_minimal() 

ggplot(war, aes(x = year, y = diff_damages))+
  geom_point() +
  labs(title="Difference in Damages With and Without Pulse",
        x ="Year", y = "Damages ($)")+
  theme_minimal() 

ggplot(war, aes(x = year, y = diff_ton))+
  geom_point() +
  labs(title="Difference in Damages Over Time From the Pulse Per Ton of
CO2 ",
        x ="Year", y = "Damages ($)")+
  theme_minimal() 

```


## Question 3

```{r scc}

discounts <- c(.01, .02, .03, .04, .05)
scc <- tribble(~c1, ~c2)
for (i in discounts){
  disc <- i
  npv <- discount(war$diff_ton, 
                  disc,
                  calculate_NPV = TRUE)
  bri <- c(disc, npv)
  scc <- rbind(scc, bri)
} 
scc <- scc %>% 
  rename("Discount_Rate" = "X0.01",
         "SCC" = "X183.316049160008")
ggplot(scc)+
  geom_line(aes(x = Discount_Rate, y = SCC))+
  labs(title="Social Cost of Carbon",
        x ="Discount Rate (%)", y = "SCC (Dollars)")+
  theme_minimal()
```


## Question 4

```{r}
#r = p + ng
r = 0.001 +(2)*(0.01)

scc_model <- lm(SCC ~ Discount_Rate, data = scc)

slope <- scc_model$coefficients[[2]]
intercept <- scc_model$coefficients[[1]]

scc_science <- r*slope + intercept

ggplot(scc)+
  geom_line(aes(x = Discount_Rate, y = SCC))+
  geom_point(x = r, y = scc_science)+
  labs(title="SCC Using Ramsey Rule",
        x ="Discount Rate (%)", y = "SCC (Dollars)")+
  theme_minimal()

```


## Question 5

```{r}

```

